# Generated by Django 2.0.7 on 2018-09-17 05:47

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180917_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
