# Generated by Django 2.0.7 on 2018-09-17 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20180917_0547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='phone',
        ),
    ]
