# Generated by Django 2.0.7 on 2018-09-17 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[('R', 'Rock'), ('J/B', 'Jazz/Blues')], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='phone_number',
            field=models.CharField(help_text='Enter your number formatted like: 09********', max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09123456789'. Up to 11 digits allowed.", regex='^\\+?09?\\d{9,15}$')]),
        ),
    ]
