# Generated by Django 2.0.7 on 2018-09-17 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180917_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='health',
            field=models.PositiveIntegerField(default=10, help_text='How healthy is your thing from 1-10?', validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(1, 'Regular'), (2, 'Special')], default='1'),
        ),
    ]
