# Generated by Django 2.0.7 on 2018-09-17 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20180917_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='health',
            field=models.PositiveIntegerField(default=10, help_text='How healthy is your thing out of 100?', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
