# Generated by Django 2.0.7 on 2018-09-26 14:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_per_day',
            field=models.DecimalField(decimal_places=0, default=12000, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_month',
            field=models.DecimalField(decimal_places=0, default=12000, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_week',
            field=models.DecimalField(decimal_places=0, default=12000, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_year',
            field=models.DecimalField(decimal_places=0, default=12000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='health',
            field=models.PositiveIntegerField(default=50, help_text='How healthy is your thing out of 100?', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='phone_number',
            field=models.CharField(help_text='Enter your number formatted like: 09123456789', max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09123456789'. Up to 11 digits allowed.", regex='^\\+?09?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(1, 'Regular'), (2, 'Promoted')], default='1'),
        ),
    ]
